#ifndef __AUTOCONF_H__
#define __AUTOCONF_H__

#define CONFIG_RING_BUFFER 1

#define CONFIG_MEMORY_ISOLATION 1

#define CONFIG_I2C_BOARDINFO 1

#define CONFIG_AEABI 1

#define CONFIG_SECCOMP 1
#define CONFIG_HIGH_RES_TIMERS 1

#define CONFIG_INOTIFY_USER 1

#define CONFIG_ARM_UNWIND 1

#define CONFIG_FSNOTIFY 1

#define CONFIG_KTIME_SCALAR 1

#define CONFIG_DEVTMPFS 1

#define CONFIG_TREE_PREEMPT_RCU 1

#define CONFIG_FORCE_MAX_ZONEORDER 11

#define CONFIG_MODULES_USE_ELF_REL 1

#define CONFIG_PRINTK 1
#define CONFIG_TIMERFD 1

#define CONFIG_MIGRATION 1

#define CONFIG_ENABLE_MUST_CHECK 1
#define CONFIG_MM_OWNER 1

#define CONFIG_SCHEDSTATS 1

#define CONFIG_CORE_DUMP_DEFAULT_ELF_HEADERS 1

#define CONFIG_PM_CLK 1

#define CONFIG_LATENCYTOP 1

#define CONFIG_ARM_L1_CACHE_SHIFT 5

#define CONFIG_BSD_PROCESS_ACCT 1

#define CONFIG_BLOCK 1

#define CONFIG_BUG 1

#define CONFIG_PM 1

#define CONFIG_MEMCG 1

#define CONFIG_SPLIT_PTLOCK_CPUS 4

#define CONFIG_SCHED_AUTOGROUP 1

#define CONFIG_ENABLE_WARN_DEPRECATED 1

#define CONFIG_TASK_XACCT 1

#define CONFIG_FS_POSIX_ACL 1

#define CONFIG_JUMP_LABEL 1

#define CONFIG_HAVE_ARCH_PFN_VALID 1
#define CONFIG_CPU_COPY_V6 1

#define CONFIG_DEBUG_BUGVERBOSE 1

#define CONFIG_CPU_V6 1

#define CONFIG_TRACE_IRQFLAGS_SUPPORT 1

#define CONFIG_DETECT_HUNG_TASK 1

#define CONFIG_BLK_CGROUP 1

#define CONFIG_LBDAF 1

#define CONFIG_OABI_COMPAT 1

#define CONFIG_NEED_MACH_MEMORY_H 1

#define CONFIG_BCACHE_MODULE 1

#define CONFIG_KEYS 1

#define CONFIG_TIMER_STATS 1

#define CONFIG_FUTEX 1

#define CONFIG_SLUB_DEBUG 1

#define CONFIG_FANOTIFY 1

#define CONFIG_CGROUP_SCHED 1
#define CONFIG_SYSVIPC 1

#define CONFIG_MODULES 1
#define CONFIG_CPU_HAS_ASID 1

#define CONFIG_NO_HZ_COMMON 1
#define CONFIG_HAVE_CLK 1

#define CONFIG_FAIR_GROUP_SCHED 1

#define CONFIG_SUSPEND 1

#define CONFIG_KPROBES 1

#define CONFIG_GENERIC_PCI_IOMAP 1
#define CONFIG_SLUB 1

#define CONFIG_PM_SLEEP 1

#define CONFIG_I2C 1

#define CONFIG_VM_EVENT_COUNTERS 1

#define CONFIG_DEBUG_FS 1

#define CONFIG_KALLSYMS 1

#define CONFIG_GENERIC_ATOMIC64 1

#define CONFIG_HAVE_HW_BREAKPOINT 1

#define CONFIG_ARM_DMA_MEM_BUFFERABLE 1

#define CONFIG_GENERIC_IRQ_PROBE 1

#define CONFIG_EPOLL 1

#define CONFIG_FREEZER 1

#define CONFIG_PREEMPT_RCU 1

#define CONFIG_POSIX_MQUEUE 1

#define CONFIG_TASKSTATS 1

#define CONFIG_NEED_DMA_MAP_STATE 1

#define CONFIG_PAGE_OFFSET 0xC0000000

#define CONFIG_NEED_MACH_IO_H 1

#define CONFIG_TTY 1

#define CONFIG_GENERIC_BUG 1

#define CONFIG_HW_CONSOLE 1

#define CONFIG_SCHED_DEBUG 1

#define CONFIG_UID16 1

#define CONFIG_HAS_DMA 1

#define CONFIG_VT_CONSOLE_SLEEP 1

#define CONFIG_RT_MUTEXES 1

#define CONFIG_KGDB 1

#define CONFIG_TASK_IO_ACCOUNTING 1

#define CONFIG_CGROUPS 1

#define CONFIG_HAS_IOPORT 1

#define CONFIG_HZ 100

#define CONFIG_SYSFS 1

#define CONFIG_ARM_THUMB 1

#define CONFIG_CC_STACKPROTECTOR 1

#define CONFIG_HAVE_GENERIC_DMA_COHERENT 1

#define CONFIG_OLD_SIGACTION 1

#define CONFIG_HAVE_ARCH_KGDB 1

#define CONFIG_MODVERSIONS 1

#define CONFIG_RWSEM_GENERIC_SPINLOCK 1
#define CONFIG_HAVE_DMA_ATTRS 1

#define CONFIG_COMPACTION 1

#define CONFIG_PROC_FS 1

#define CONFIG_FLATMEM 1

#define CONFIG_PAGEFLAGS_EXTENDED 1

#define CONFIG_SYSCTL 1

#define CONFIG_TASK_DELAY_ACCT 1

#define CONFIG_AUDIT 1

#define CONFIG_SECCOMP_FILTER 1

#define CONFIG_FLAT_NODE_MEM_MAP 1

#define CONFIG_PREEMPT 1

#define CONFIG_CPU_USE_DOMAINS 1

#define CONFIG_QUOTA 1

#define CONFIG_HAVE_MOD_ARCH_SPECIFIC 1

#define CONFIG_SWAP 1

#define CONFIG_MODULE_UNLOAD 1

#define CONFIG_PREEMPT_COUNT 1

#define CONFIG_CMA 1

#define CONFIG_FILE_LOCKING 1

#define CONFIG_AIO 1

#define CONFIG_PERF_EVENTS 1

#define CONFIG_GENERIC_HARDIRQS 1

#define CONFIG_MMU 1

#define CONFIG_KUSER_HELPERS 1

#endif /* ! __AUTOCONF_H__ */
